### PR TITLE
Remove the no-return-await rule

### PR DESCRIPTION
**Pull request by nickdaugherty**
It turns out that `return await` is actually helpful because it improves stack traces https://www.even.li/posts/2020-06-04-async-stack-traces/

Props @robersongomes for the idea!

### CODE REVIEW

**Review by robersongomes — DISMISSED** [review]
LGTM

**Comment by nickdaugherty** [comment]
Props @robersongomes for the idea!

**Comment by joshbetz** [comment]
Props @robersongomes for the idea!

**Comment by nickdaugherty** [comment]
Finally got the builds working - turns out our dependency caching on CircleCI was pretty busted so it kept running against old dependencies.

**Pull request merged**
