### PR TITLE
Disable camelcase rules

### PR DESCRIPTION
**Pull request by nickdaugherty**
Can't get away from underscore case, it's everywhere, such as in requests and responses for API's, legacy code, etc. Rather than accept tons of warnings or annotate every single line with a disabling comment, let's just drop the rule.

### CODE REVIEW

**Comment by mjangda** [comment]
Instead of turning it off completely, maybe we should just set `properties: never` and `ignoreDestructuring: true`?

https://eslint.org/docs/rules/camelcase#options

**Comment by nickdaugherty** [comment]
Oh I like that a lot better, let me try that out...

**Comment by nickdaugherty** [comment]
@mjangda I've switched over to those options and they work great.

**Comment by nickdaugherty** [comment]
NOTE - configuring multiple options at the same time requires eslint 5.x, so dropped the 3.x and 4.x peerDependencies.

**Review by mjangda — APPROVED** [review]

**Pull request merged**
